# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-pyqtads-linux:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install build virtualenv
        sudo apt install qtbase5-private-dev
        virtualenv my_venv 
        . my_venv/bin/activate 
        pip install PyQt5 PyQt-builder sip 
    - name: Package
      run: |
        . my_venv/bin/activate 
        sip-wheel --build-dir build  --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: linux-packages
        path: ./*.whl


